/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crudfile;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class Createfile extends javax.swing.JFrame {

    /**
     * Creates new form Createfile
     */
    public Createfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeetable = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        EmployeeID = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        StartDate = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Level = new javax.swing.JLabel();
        Teaminfo = new javax.swing.JLabel();
        Positiontitle = new javax.swing.JLabel();
        cellphone_no = new javax.swing.JLabel();
        emailid = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfEmployeeID = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        tfStartDate = new javax.swing.JTextField();
        tfGender = new javax.swing.JTextField();
        tfLevel = new javax.swing.JTextField();
        tfTeamInfo = new javax.swing.JTextField();
        tfPosition = new javax.swing.JTextField();
        tfcellphone = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        SAVEBUTTON = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        View = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeetable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeetable.setText("                                                  Employee Details ");

        Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Name.setText("Name");

        EmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeID.setText("EmployeeID:");

        Age.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Age.setText("Age:");

        StartDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StartDate.setText("StartDate");

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gender.setText("Gender");

        Level.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Level.setText("Level");

        Teaminfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Teaminfo.setText("Teaminfo");

        Positiontitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Positiontitle.setText("Position title");

        cellphone_no.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cellphone_no.setText("cellphone_no");

        emailid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailid.setText("emailid");

        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });

        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });

        SAVEBUTTON.setText("SAVE");
        SAVEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEBUTTONActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("SEARCH");

        View.setText("VIEW");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        update.setText("UPDATE");

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EmployeeID", "Age", "Gender", "Level"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(employeetable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(SAVEBUTTON)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cellphone_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Positiontitle)
                            .addComponent(Teaminfo)
                            .addComponent(Level)
                            .addComponent(Gender)
                            .addComponent(EmployeeID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfcellphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(tfPosition, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTeamInfo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLevel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGender, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStartDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmployeeID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfemail)))
                    .addComponent(Name)
                    .addComponent(Age)
                    .addComponent(StartDate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(View)
                        .addGap(41, 41, 41)
                        .addComponent(update)
                        .addGap(36, 36, 36)
                        .addComponent(Delete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeetable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View)
                    .addComponent(update)
                    .addComponent(Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeID)
                    .addComponent(tfEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age)
                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartDate)
                            .addComponent(tfStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender)
                            .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Level)
                            .addComponent(tfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Teaminfo)
                    .addComponent(tfTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Positiontitle)
                    .addComponent(tfPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellphone_no)
                    .addComponent(tfcellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailid)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVEBUTTON)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewActionPerformed

    private void SAVEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEBUTTONActionPerformed
        // TODO add your handling code here:
        
        if(tfName.getText().equals("")||tfEmployeeID.getText().equals("")||tfAge.getText().equals("")||tfStartDate.getText().equals("")||tfGender.getText().equals("")||tfLevel.getText().equals("")||tfTeamInfo.getText().equals("")||tfPosition.getText().equals("")||tfcellphone.getText().equals("")||tfemail.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please Enter All Details"); 
    }//GEN-LAST:event_SAVEBUTTONActionPerformed

         else{
            String data[]={tfName.getText(),tfGender.getText(),tfEmployeeID.getText(),tfAge.getText(),tfStartDate.getText(),tfLevel.getText(),tfTeamInfo.getText(),tfPosition.getText(),tfcellphone.getText(),tfemail.getText()};
            DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(data);
                JOptionPane.showMessageDialog(this,"Add Data Successfully!");
                 tfName.setText("");
                 tfEmployeeID.setText("");
                 tfAge.setText("");
                 tfStartDate.setText("");
                 tfLevel.setText("");
                 tfTeamInfo.setText("");
                 tfPosition.setText("");
                 tfcellphone.setText("");
                 tfemail.setText("");
        }
    }
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
        
        if(jTable1.getSelectedRowCount()==1)
        {
            tb1Model.removeRow(jTable1.getSelectedRow());
        }
        else{
            if(jTable1.getRowCount()==0)
            {
             JOptionPane.showMessageDialog(this,"Table is Empty!");   
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please select single row for deletion");
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed
       
                 
        
    
       
        
                
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel EmployeeID;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Level;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Positiontitle;
    private javax.swing.JButton SAVEBUTTON;
    private javax.swing.JLabel StartDate;
    private javax.swing.JLabel Teaminfo;
    private javax.swing.JButton View;
    private javax.swing.JLabel cellphone_no;
    private javax.swing.JLabel emailid;
    private javax.swing.JLabel employeetable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfEmployeeID;
    private javax.swing.JTextField tfGender;
    private javax.swing.JTextField tfLevel;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPosition;
    private javax.swing.JTextField tfStartDate;
    private javax.swing.JTextField tfTeamInfo;
    private javax.swing.JTextField tfcellphone;
    private javax.swing.JTextField tfemail;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}




